<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by Vue-Basket</title>
</head>
<body>
<h1>{{ $infos['name'] }}</h1>
<p>{{ $infos['info'] }}</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet asperiores dignissimos eligendi esse excepturi fugiat hic illum ipsam, maiores minus nulla obcaecati quam quibusdam quidem ratione suscipit tenetur veritatis voluptatibus.</p>
</body>
</html>
